// Generated by app/scripts/sync-data.mjs from articles/baby-kids-101.html.
// Edit the article, not this file. Bundled into the worker, never into the app.
export const KIDS = {
 "title": "Kids",
 "sub": "Kids",
 "focus": "Bottles and feeding, the nursery, wipes and creams, in the order that matters for someone that small.",
 "steps": [
  {
   "id": "Kids::Move bottles and cups to glass or steel",
   "swap": "Move bottles and cups to glass or steel",
   "why": "Heated formula in a plastic bottle is one of the highest microplastic doses measured anywhere, up to 16 million particles per liter.",
   "heat": true,
   "free": "Never heat formula in the bottle. Mix in glass, cool it, then transfer. That removes most of it today.",
   "picks": [
    {
     "label": "$",
     "name": "Evenflo Classic Glass Bottles (8oz, 6 pack)",
     "url": "https://www.amazon.com/dp/B019PG0FPO?tag=plasticdetox-20",
     "note": "Best value glass bottle"
    },
    {
     "label": "$",
     "name": "Klean Kanteen Kid Classic (12oz)",
     "url": "https://www.amazon.com/dp/B0DK7J39YJ?tag=plasticdetox-20",
     "note": "Best kids stainless bottle"
    },
    {
     "label": "$",
     "name": "REDECKER Bottle Brush Cleaner",
     "url": "https://www.amazon.com/dp/B002HORIN4?tag=plasticdetox-20",
     "note": "Best plastic free bottle brush"
    }
   ]
  },
  {
   "id": "Kids::Choose a cleaner formula",
   "swap": "Choose a cleaner formula",
   "why": "The entire diet for months, and formula has tested for heavy metals and seed oil contaminants.",
   "heat": false,
   "free": "None, but preparing with filtered water is the cheapest improvement you can make.",
   "picks": [
    {
     "label": "$$$",
     "name": "Bobbie Organic Infant Formula",
     "url": "https://www.amazon.com/dp/B0DY1V2T7H?tag=plasticdetox-20",
     "note": "Best clean tested formula"
    }
   ]
  },
  {
   "id": "Kids::Change how you buy baby food",
   "swap": "Change how you buy baby food",
   "why": "Pouches are plastic against warm puree, and commercial baby food has repeatedly tested high for heavy metals.",
   "heat": true,
   "free": "Mash whatever you are eating. Free, and better food than any jar.",
   "picks": [
    {
     "label": "$",
     "name": "One Degree Organics Sprouted Rolled Oats",
     "url": "https://www.amazon.com/dp/B0B4V5TBLJ?tag=plasticdetox-20",
     "note": "Best glyphosate tested baby oats"
    }
   ]
  },
  {
   "id": "Kids::Replace plastic teethers",
   "swap": "Replace plastic teethers",
   "why": "An object designed to be chewed on for hours, by someone who cannot tell you it tastes wrong.",
   "heat": false,
   "free": "A clean, chilled cotton washcloth is the classic teether and costs nothing.",
   "picks": [
    {
     "label": "$",
     "name": "Untreated Hardwood Teether",
     "url": "https://www.amazon.com/dp/B004P9S8W4?tag=plasticdetox-20",
     "note": "Best wooden teether"
    },
    {
     "label": "$",
     "name": "Medical Grade Silicone Teether",
     "url": "https://www.amazon.com/dp/B09BVXG63Z?tag=plasticdetox-20",
     "note": "Best medical grade option"
    }
   ]
  },
  {
   "id": "Kids::Replace plates, bowls, and utensils",
   "swap": "Replace plates, bowls, and utensils",
   "why": "Hot food on plastic plates, every meal, for years. Melamine kids dishes leach more the hotter the food.",
   "heat": true,
   "free": "Use your normal small plates and let them learn on ceramic. Breakage is cheaper than replacement gear.",
   "picks": [
    {
     "label": "$",
     "name": "Avanchy Stainless Steel Baby Spoons",
     "url": "https://www.amazon.com/dp/B07K1FFK6Z?tag=plasticdetox-20",
     "note": "Best utensil pick"
    },
    {
     "label": "$",
     "name": "ezpz Mini Mat Silicone Plate",
     "url": "https://www.amazon.com/dp/B01C95ZCNI?tag=plasticdetox-20",
     "note": "Best silicone plate"
    },
    {
     "label": "$$",
     "name": "Ahimsa Stainless Steel Bowl and Plate Set",
     "url": "https://www.amazon.com/dp/B0C6SVTQ3Q?tag=plasticdetox-20",
     "note": "Best stainless tableware"
    }
   ]
  },
  {
   "id": "Kids::Change your diaper brand",
   "swap": "Change your diaper brand",
   "why": "Against the most permeable skin on the body, 24 hours a day, for roughly three years. Several major brands have tested positive for PFAS.",
   "heat": false,
   "free": "Change more frequently. Contact time is the variable you control for free.",
   "picks": [
    {
     "label": "$$$",
     "name": "Coterie Diapers",
     "url": "https://www.amazon.com/dp/B0DKPJHFGS?tag=plasticdetox-20&amp;th=1",
     "note": "Best overall diaper"
    },
    {
     "label": "$",
     "name": "Eco by Naty Diapers",
     "url": "https://www.amazon.com/dp/B07FTPBBK9?tag=plasticdetox-20",
     "note": "Cheapest clean diaper"
    },
    {
     "label": "$$",
     "name": "Seventh Generation Sensitive Skin Diapers",
     "url": "https://www.amazon.com/dp/B084H4H6HR?tag=plasticdetox-20",
     "note": "Easiest to find"
    }
   ]
  },
  {
   "id": "Kids::Change your wipes",
   "swap": "Change your wipes",
   "why": "Most wipes are polyester fabric soaked in preservative solution, used dozens of times a day on broken skin.",
   "heat": false,
   "free": "Cotton washcloths and warm water. Cheaper over three years than any wipe.",
   "picks": [
    {
     "label": "$$$",
     "name": "Coterie The Wipe",
     "url": "https://www.amazon.com/dp/B0DMWQ1QQT?tag=plasticdetox-20",
     "note": "Best overall wipe, our top pick"
    },
    {
     "label": "$",
     "name": "Caboo Tree Free Baby Wipes",
     "url": "https://www.amazon.com/dp/B01LOPQYHW?tag=plasticdetox-20",
     "note": "Best value clean wipe"
    },
    {
     "label": "$",
     "name": "Marley's Monsters Organic Cloth Wipes",
     "url": "https://www.amazon.com/dp/B0BGNJVWTH?tag=plasticdetox-20",
     "note": "Best reusable cloth wipes"
    }
   ]
  },
  {
   "id": "Kids::Change your diaper cream",
   "swap": "Change your diaper cream",
   "why": "Applied thickly to already irritated skin, which absorbs far more than intact skin does.",
   "heat": false,
   "free": "Plain zinc oxide or lanolin. The simplest formulas are usually the cheapest ones.",
   "picks": [
    {
     "label": "$$",
     "name": "La Petite Creme Organic Diaper Balm",
     "url": "https://www.amazon.com/dp/B07HM7KVKW?tag=plasticdetox-20",
     "note": "Only diaper balm lab tested clean, our top pick"
    },
    {
     "label": "$$",
     "name": "Motherlove Diaper Balm",
     "url": "https://www.amazon.com/dp/B000XJ2LDW?tag=plasticdetox-20",
     "note": "Best for cloth diapers"
    }
   ]
  },
  {
   "id": "Kids::Change baby wash and shampoo",
   "swap": "Change baby wash and shampoo",
   "why": "Thinner skin, higher surface area relative to body weight, and a developing system. Fragrance is the main issue.",
   "heat": false,
   "free": "Bathe with water only for the first months. Recommended anyway, and free.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/baby-kids-101.html"
    }
   ]
  },
  {
   "id": "Kids::Set up the nursery without offgassing",
   "swap": "Set up the nursery without offgassing",
   "why": "New furniture, foam, and paint offgas hardest in the first months, straight into a small room where an infant sleeps 16 hours a day.",
   "heat": false,
   "free": "Assemble and air out everything for two to four weeks before the baby uses the room. Free and genuinely effective.",
   "picks": [
    {
     "label": "$",
     "name": "Yogasleep Dohm Classic White Noise Machine",
     "url": "https://www.amazon.com/dp/B00HD0ELFK?tag=plasticdetox-20",
     "note": "Best mechanical white noise"
    }
   ]
  },
  {
   "id": "Kids::Replace foam play mats",
   "swap": "Replace foam play mats",
   "why": "EVA foam mats offgas into the exact 30cm of air where a crawling baby breathes, all day.",
   "heat": false,
   "free": "A cotton quilt or wool rug on the floor does the same job.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/non-toxic-baby-toddler-products-guide.html"
    }
   ]
  },
  {
   "id": "Kids::Make and store baby food in glass",
   "swap": "Make and store baby food in glass",
   "why": "Steaming and blending in a plastic chamber puts heat, fat, and plastic together at once.",
   "heat": true,
   "free": "A fork and a pot. Purees do not need equipment.",
   "picks": [
    {
     "label": "$",
     "name": "Sage Spoonfuls Stainless Steel Steamer Basket",
     "url": "https://www.amazon.com/dp/B00PK49HVO?tag=plasticdetox-20",
     "note": "Best minimal BLW option"
    },
    {
     "label": "$$",
     "name": "Bear NutriEase AllStage Baby Food Maker",
     "url": "https://www.amazon.com/dp/B0FL7K9WMX?tag=plasticdetox-20",
     "note": "Best all in one with stainless steel pathway"
    }
   ]
  },
  {
   "id": "Kids::Replace plastic and silicone bibs",
   "swap": "Replace plastic and silicone bibs",
   "why": "PVC bibs sit against the neck and chest through every meal, and end up in the mouth constantly.",
   "heat": false,
   "free": "An old cotton towel tucked into the collar.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/non-toxic-baby-toddler-products-guide.html"
    }
   ]
  },
  {
   "id": "Kids::Replace bath toys and tub gear",
   "swap": "Replace bath toys and tub gear",
   "why": "Squeeze toys hold warm water and grow mold inside, and most are PVC that a child puts in their mouth.",
   "heat": true,
   "free": "Throw out the squeeze toys. Cups and a ladle are better bath toys anyway.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/non-toxic-baby-toddler-products-guide.html"
    }
   ]
  },
  {
   "id": "Kids::Consider cloth for part of the day",
   "swap": "Consider cloth for part of the day",
   "why": "Removes the disposable question entirely for the hours you use it, and pays back over three years.",
   "heat": false,
   "free": "Even part time cloth, at home only, cuts disposable contact substantially.",
   "picks": [
    {
     "label": "$",
     "name": "EcoAble Hemp Inserts",
     "url": "https://www.amazon.com/dp/B07PPQ3Y2S?tag=plasticdetox-20",
     "note": "Best overnight booster"
    },
    {
     "label": "$$",
     "name": "Rumparooz One Size",
     "url": "https://www.amazon.com/dp/B0GH5JMW2K?tag=plasticdetox-20",
     "note": "Best waterproof layer"
    }
   ]
  },
  {
   "id": "Kids::Shift toys to wood and natural fiber",
   "swap": "Shift toys to wood and natural fiber",
   "why": "Anything a small child holds ends up in the mouth, and soft plastic toys are a phthalate source.",
   "heat": false,
   "free": "Stop buying new plastic toys. Attrition handles the rest without a single purchase.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/non-toxic-baby-toddler-products-guide.html"
    }
   ]
  },
  {
   "id": "Kids::Move kids clothing to natural fiber",
   "swap": "Move kids clothing to natural fiber",
   "why": "Polyester against skin all day, and flame retardant treatments are still common in children's sleepwear.",
   "heat": false,
   "free": "Wash everything new before first wear, and buy secondhand cotton. Used natural fiber beats new synthetic.",
   "picks": [
    {
     "label": "$",
     "name": "aden + anais Cotton Muslin Swaddle",
     "url": "https://www.amazon.com/dp/B0DVCGX73C?tag=plasticdetox-20",
     "note": "Best breathable swaddle"
    }
   ]
  },
  {
   "id": "Kids::Choose a wood or steel high chair",
   "swap": "Choose a wood or steel high chair",
   "why": "A plastic tray holding hot food, every meal, for two years.",
   "heat": true,
   "free": "Put a plate on the tray instead of food directly on it.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/non-toxic-baby-toddler-products-guide.html"
    }
   ]
  },
  {
   "id": "Kids::Choose an organic nursing pillow",
   "swap": "Choose an organic nursing pillow",
   "why": "Polyurethane foam pressed against both of you for hours a day during the newborn months.",
   "heat": false,
   "free": "Stacked pillows you already own work, and many people prefer them.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/non-toxic-baby-toddler-products-guide.html"
    }
   ]
  },
  {
   "id": "Kids::Pump into glass",
   "swap": "Pump into glass",
   "why": "Warm milk into plastic flanges and bottles, several times a day. Milk is high fat, which pulls more out of plastic.",
   "heat": true,
   "free": "Transfer to glass immediately after pumping instead of storing in the plastic bottle.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/best-non-toxic-baby-bottles.html"
    }
   ]
  },
  {
   "id": "Kids::Choose a natural fiber carrier",
   "swap": "Choose a natural fiber carrier",
   "why": "Hours of direct contact against a newborn's face and hands, usually in synthetic mesh.",
   "heat": false,
   "free": "A woven cotton wrap is the cheapest carrier and the most natural.",
   "picks": [
    {
     "label": "Guide",
     "name": "Read the full guide",
     "url": "https://plasticdetox.org/articles/non-toxic-baby-toddler-products-guide.html"
    }
   ]
  },
  {
   "id": "Kids::Choose a flame retardant free car seat",
   "swap": "Choose a flame retardant free car seat",
   "why": "Enclosed, heated by sun, and federally required to meet flammability standards that many brands still meet chemically.",
   "heat": true,
   "free": "Air out a new seat outside for two weeks, and crack the windows on hot days before the child gets in.",
   "picks": [
    {
     "label": "$$$",
     "name": "Clek Foonf Convertible Car Seat",
     "url": "https://www.amazon.com/dp/B0CZPCGF51?tag=plasticdetox-20",
     "note": "Best flame retardant free car seat"
    }
   ]
  },
  {
   "id": "Kids::Choose a cleaner stroller fabric",
   "swap": "Choose a cleaner stroller fabric",
   "why": "Lowest priority kids purchase here. Real exposure, but far less contact time than anything above it.",
   "heat": false,
   "free": "Air out a new stroller before use and skip the water repellent treatments.",
   "picks": [
    {
     "label": "$$$$",
     "name": "Bugaboo Fox Premium Stroller",
     "url": "https://www.amazon.com/dp/B0F1DPY9QC?tag=plasticdetox-20",
     "note": "Best disclosed material stroller"
    },
    {
     "label": "$$$$",
     "name": "UPPAbaby Vista Stroller",
     "url": "https://www.amazon.com/dp/B0D9XS9VXL?tag=plasticdetox-20",
     "note": "Best for growing families"
    }
   ]
  }
 ]
};
