#!/usr/bin/env python3
"""
Audit every product row in brand-data.json against docs/rating-rules.md.

This is the extension's standard, not Brand Check's. The extension speaks about
one product at a time, on a listing page, at the moment of purchase, so it is
held to the strict rule: a recommendation needs direct evidence about the thing
being looked at. Brand Check keeps its brand level view and rolls product rows up
instead. See tools/brand-rollup.py for that half.

What it checks, in the order the rules document sets them out:

  1.1  favourable evidence never propagates, so an inherited row cannot be good
  2    an unobtainable ingredient list is a caution, not an unknown
  4.3  a non detect without a limit of detection cannot be cited as a pass
  5.1  a filed but unresolved suit caps at careful, only a resolution reaches skip
  5.2  a closed and remedied recall over 24 months old is informational
  5.3  absence of a recall is not a pass, and can never be the reason for a good
  6    aggregation, and the direct evidence requirement for good

Reports only. Writing is tools/apply-product-rules.py, so a bad classification
run can never silently rewrite published verdicts.

    python3 tools/audit-product-rules.py
    python3 tools/audit-product-rules.py --strict     # good needs all four fronts
    python3 tools/audit-product-rules.py --show skip  # list every row of one change
    python3 tools/audit-product-rules.py --json out.json
"""

import argparse
import collections
import datetime
import importlib.util
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "brand-data.json"
FRONTS = ("formula", "packaging", "legal", "testing")
TODAY = datetime.date(2026, 8, 28)

# Reuse the classifier rather than growing a second, divergent copy of it.
_spec = importlib.util.spec_from_file_location(
    "backfill_fronts", ROOT / "tools" / "backfill-fronts.py")
_bf = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_bf)


# ---------------------------------------------------------------- scope, basis

def scope_of(prod):
    """
    Which scope the row's evidence actually covers.

    An ASIN list is a claim about those exact listings. A `match` phrase is a
    named product line, written by hand during research. A `matchAll` group is
    brand words plus a category word, which is a brand level claim narrowed to a
    category, and that is the broadest thing the extension is allowed to show.
    """
    if prod.get("asins"):
        return "sku"
    if prod.get("match"):
        return "line"
    if prod.get("matchAll"):
        return "brand"
    return "none"


def basis_of(prod):
    # brand-line rows are generated by projecting a brand verdict onto a
    # category. Everything else was written against a specific product.
    return "inherited" if prod.get("origin") == "brand-line" else "direct"


# ----------------------------------------------------------------- front rules

NO_RECALL = re.compile(
    r"\bno (cpsc |fda )?(recall|recalls|lawsuit|lawsuits|class action|filed|"
    r"open recall|reported)\b|\b(closed|ended) without\b|\bnone found\b")
FILED_ONLY = re.compile(r"\b(filed|pending|alleges|alleging|allegation|"
                        r"proposed class|complaint)\b")
RESOLVED = re.compile(r"\b(settled|settlement|judgment|judgement|consent decree|"
                      r"fined|penalty|verdict|ruled|injunction|recalled|recall)\b")
NON_DETECT = re.compile(r"\bnon[\s-]?detect\w*|\bnot detected\b|\bbelow detection\b|"
                        r"\bno lead detected\b|\bundetected\b")
HAS_LOD = re.compile(r"\b(lod|limit of detection|detection limit)\b|"
                     r"\b\d+(\.\d+)?\s?(ppb|ppm|µg|ug|mg)/?\w*\b")
AB1200_ONLY = re.compile(r"\bab ?1200\b")
NO_INGREDIENTS = re.compile(
    r"\b(does not (publish|disclose)|undisclosed|not disclosed|proprietary blend|"
    r"no ingredient list|does not list)\b")
RECALL_YEAR = re.compile(r"\b(19|20)\d{2}\b")


# Store and registry notes carry two kinds of text that are not claims about the
# product: a trailing caveat list, and contrast clauses naming the bad thing this
# product replaces. Classified raw, "a direct swap for the nylon pouf, which
# sheds microplastics" reads as a loofah that sheds microplastics, and
# "Skip bamboo rayon swaddles" reads as an organic cotton swaddle made of rayon.
# Both produced a skip on a researched recommendation, which is the exact
# trade-libel shape the classifier is written to avoid.
CAVEAT = re.compile(r"\bworth knowing\s*:.*$", re.I | re.S)
CONTRAST_CLAUSE = re.compile(
    r"(?:^|(?<=[.;,]))\s*(?:skip|avoid|unlike|instead of|rather than|compared to|"
    r"as opposed to|not like|a (?:direct )?(?:swap|replacement|alternative) for)\b[^.;]*",
    re.I)


# A source's name is provenance, not a finding. "Lead Safe Mama" put the word
# lead into every note citing them, which cancelled out the very non-detect they
# had published: Weleda Salt Toothpaste, a non detect at a 5 ppb limit, scored
# one hazard against one clean result and came out neutral.
SOURCE_NAMES = re.compile(
    r"\blead safe mama\b|\bconsumer reports\b|\bclean label project\b|"
    r"\bdetox project\b|\bmade safe\b|\bgreenpeace\b", re.I)


def clean_note(note):
    """Strip caveats, contrast clauses and source names so only claims remain."""
    n = CAVEAT.sub("", note or "")
    n = CONTRAST_CLAUSE.sub(" ", n)
    n = SOURCE_NAMES.sub("the lab", n)
    return re.sub(r"\s+", " ", n).strip()


# The classifier was written for brand prose, where a claim comes wrapped in
# argument. Store and registry notes are spec sheets: "18/8 stainless", "100%
# cotton muslin", "medical grade borosilicate glass". Those name the material
# outright and carry no argument for the polarity test to grip, so the formula
# front came back unknown on rows whose formula is the most certain thing about
# them. Naming an inert material with no hazard term anywhere in the note is a
# formula pass, and that is all rule 2 ever asked for.
INERT = [
    "stainless", "18/8", "18/10", "304 steel", "316 steel", "borosilicate",
    "tempered glass", "glass", "cast iron", "carbon steel", "enamel", "enameled",
    "organic cotton", "cotton", "muslin", "linen", "hemp", "wool", "merino",
    "silk", "tencel", "lyocell", "jute", "sisal", "loofah", "plant fiber",
    "plant fibre", "solid wood", "maple", "beech", "birch", "bamboo fiber",
    "beeswax", "paper", "unbleached", "food grade silicone", "platinum silicone",
    "titanium", "copper", "brass", "porcelain", "stoneware", "clay", "cork",
    "natural rubber", "latex free", "aluminium free", "aluminum free",
]
HAZARD = [
    "plastic", "polyester", "nylon", "acrylic", "spandex", "elastane",
    "ptfe", "teflon", "nonstick", "non-stick", "pfoa", "pfas", "pvc",
    "polycarbonate", "polypropylene", "polyethylene", "polystyrene", "styrene",
    "melamine", "viscose", "rayon", "neoprene", "phthalate", "paraben",
    "fragrance", "parfum", "formaldehyde", "triclosan", "flame retardant",
    "bpa", "bps", "bpf", "lead", "cadmium", "azo", "chemical filter",
]


# For a durable good the object IS its material, so formula and packaging are one
# front and a fully specified inert material is the complete safety case. A
# stainless bowl with no coating has nothing further to disclose, and demanding a
# lab result before recommending one is not a standard, it is a blocker.
#
# For a consumable the two come apart. The formula is a recipe, the packaging is
# a separate object that can migrate into it, and lab testing routinely finds
# what the ingredient list cannot show. There the second front is real, so the
# rules default applies unchanged.
CONSUMABLE_WORDS = (
    "cosmetic", "personal care", "sunscreen", "skincare", "supplement",
    "bottled water", "food", "formula", "electrolyte", "oral care", "cleaning",
    "laundry", "coffee bean", "salt", "diaper cream", "diaper", "wipe",
    "period", "deodorant", "toothpaste", "spice", "protein", "pantry",
)
DURABLE_OVERRIDE = ("cloth diaper", "diaper bag", "diaper pail", "food storage",
                    "baby food storage", "food prep")


def is_consumable(category, product_name=""):
    cat = (category or "").lower()
    if any(w in cat for w in DURABLE_OVERRIDE):
        return False
    return any(w in cat for w in CONSUMABLE_WORDS)


def formula_from_materials(note):
    """
    'pass' when the note names an inert material and no hazard, else None.

    Hazard words that the copy explicitly rules out do not count, so
    "no interior coating", "BPA free cap" and "phthalate free" stay passes.
    """
    low = " " + (note or "").lower() + " "
    for h in HAZARD:
        for m in re.finditer(r"(?<![a-z0-9])" + re.escape(h) + r"(?![a-z0-9])", low):
            if not _bf.is_negated(low, m.start(), m.end()):
                return None
    return "pass" if any(_bf.has(low, t) for t in INERT) else None


def fronts_for(prod, brand):
    """Classify the row's own note. Never falls back to the brand's prose."""
    if prod.get("fronts") and prod["fronts"].get("authored"):
        return {f: prod["fronts"][f] for f in FRONTS if f in prod["fronts"]}, True
    pseudo = {"reason": clean_note(prod.get("note")), "evidence": "", "stance": None}
    return _bf.build_fronts(pseudo), False


def apply_rules(fronts, note, scope, basis):
    """
    Fold the rules document's per-front corrections into a classified scorecard.
    Returns the corrected fronts plus the list of rules that fired.
    """
    low = (note or "").lower()
    fired = []
    f = {k: dict(v) for k, v in fronts.items()}

    # 5.3  absence of a recall is not a pass. Barely regulated categories produce
    #      no recalls because nobody is looking, not because nothing is wrong.
    if f["legal"]["status"] == "pass" and NO_RECALL.search(low) and not RESOLVED.search(low):
        f["legal"] = {"status": "unassessed", "note": "Checked, nothing found.",
                      "origin": "rule-5.3"}
        fired.append("5.3 no-recall-is-not-a-pass")

    # 5.1  a filed suit is an allegation. Only a resolution can fail the front.
    if f["legal"]["status"] == "fail" and FILED_ONLY.search(low) and not RESOLVED.search(low):
        f["legal"]["status"] = "caution"
        fired.append("5.1 filed-suit-caps-at-caution")

    # 5.2  a closed, remedied recall older than 24 months is informational.
    if f["legal"]["status"] in ("fail", "caution") and "recall" in low:
        years = [int(y) for y in RECALL_YEAR.findall(low)]
        if years and max(years) <= TODAY.year - 3 and re.search(
                r"\b(closed|remedied|resolved|fixed|corrected|since)\b", low):
            f["legal"] = {"status": "unassessed",
                          "note": f["legal"].get("note", ""), "origin": "rule-5.2"}
            fired.append("5.2 recall-decayed")

    # 4.3  a non detect is not comparable, and not citable, without its limit.
    if f["testing"]["status"] == "pass" and NON_DETECT.search(low) and not HAS_LOD.search(low):
        f["testing"]["status"] = "unassessed"
        fired.append("4.3 non-detect-without-lod")

    # 4.3 stated positively. A non detect reported WITH its limit is exactly what
    # the rule asks for and is citable as a pass. The classifier could not see
    # this: it knows "non-detect" hyphenated but not "non detect" spaced, and it
    # holds no positive term for a clean result at a stated limit at all. Weleda
    # Salt Toothpaste, a non detect at 5 ppb and one of three pastes in the guide
    # to clear the line, scored nothing on the only front it has evidence for.
    if (f["testing"]["status"] in ("unknown", "unassessed")
            and NON_DETECT.search(low) and HAS_LOD.search(low)):
        f["testing"] = {"status": "pass",
                        "note": "Non detect at a stated limit of detection.",
                        "origin": "rule-4.3"}
        fired.append("4.3 non-detect-with-lod-is-a-pass")

    # 5.3 again, on the formula front. An AB 1200 disclosure existing is a legal
    #     front nothing. It is not evidence about what is in the pan.
    if f["formula"]["status"] == "pass" and AB1200_ONLY.search(low):
        strong = re.search(r"\bdiscloses no\b|\bno intentionally added\b", low)
        if not strong:
            f["formula"]["status"] = "unassessed"
            fired.append("5.3 ab1200-disclosure-is-not-a-formula-pass")

    # 2  an ingredient list we cannot obtain is a finding, not an absence of one.
    if f["formula"]["status"] in ("unknown", "unassessed") and NO_INGREDIENTS.search(low):
        f["formula"] = {"status": "caution",
                        "note": "The manufacturer does not publish a complete ingredient list.",
                        "origin": "rule-2"}
        fired.append("2 non-disclosure-is-a-caution")

    # Rule 2: formula is always resolvable, so read the material directly when
    # the classifier's polarity test found nothing to grip on.
    if f["formula"]["status"] in ("unknown", "unassessed"):
        if formula_from_materials(note) == "pass":
            f["formula"] = {"status": "pass", "note": "Materials named in the listing.",
                            "origin": "rule-2-materials"}
            fired.append("2 formula-read-from-materials")

    # normalise the classifier's "unknown" to the rules document's vocabulary
    for k in f:
        if f[k].get("status") == "unknown":
            f[k]["status"] = "unassessed"
    return f, fired


WEAK_ONLY = re.compile(
    r"^(?:[^.]*\b(?:no (?:cpsc |fda )?recall|no (?:filed|open) |none found|"
    r"ab ?1200|discloses|non[\s-]?detect)\b[^.]*[.]?\s*)+$")


def correct(old, f, note, scope, basis, strict=False, lenient=False, consumable=True):
    """
    Section 6, applied as a correction rather than a re-adjudication.

    The verdict already on the row was written by a person, either directly or
    in a ranked article table. That judgement is evidence and the rules do not
    discard it. What the rules govern is whether it is allowed to travel, and
    whether the evidence under a recommendation is strong enough to carry one.

    Returns (verdict, reason, needs_disclosure).
    """
    low = (note or "").lower()
    st = {k: f[k]["status"] for k in FRONTS}

    # ---- adverse verdicts -------------------------------------------------
    # 1.1 adverse evidence may propagate, so an inherited caution or skip
    # stands. 1.2 requires the copy to name the scope it came from.
    if old in ("careful", "skip"):
        # 5.1 a filed but unresolved suit is an allegation. If that is the only
        # adverse finding on the row, it caps at careful.
        if old == "skip" and FILED_ONLY.search(low) and not RESOLVED.search(low):
            adverse = [k for k in FRONTS if st[k] in ("fail", "caution")]
            if adverse in ([], ["legal"]):
                return "careful", "a filed suit is an allegation, capped at careful", basis != "direct"
        # 5.2 a closed and remedied recall over 24 months old is informational.
        if "recall" in low:
            years = [int(y) for y in RECALL_YEAR.findall(low)]
            remedied = re.search(r"\b(closed|remedied|resolved|fixed|corrected)\b", low)
            if years and remedied and max(years) <= TODAY.year - 3:
                adverse = [k for k in FRONTS if st[k] in ("fail", "caution")]
                if adverse in ([], ["legal"]):
                    return "unrated", f"recall closed and remedied in {max(years)}, now informational", False
        return old, "adverse finding stands", basis != "direct"

    # ---- neutral ----------------------------------------------------------
    # Not a verdict in the rules vocabulary. It asserts nothing, so it renders
    # as the state that asserts nothing.
    if old == "neutral":
        return "unrated", "neutral is not a verdict, nothing is being asserted", False

    # ---- recommendations --------------------------------------------------
    # 1.1 favourable evidence never propagates. This is the whole Sensarte fix.
    if basis != "direct":
        return "unrated", "a recommendation cannot rest on inherited evidence", False
    if scope not in ("sku", "line"):
        return "unrated", f"a recommendation needs sku or line scope, this is {scope}", False

    # 5.3 absence of a recall is not a pass, and an AB 1200 disclosure existing
    # is a legal front nothing. Neither can be the reason something is good.
    # 4.3 a non detect without its limit of detection is not citable either.
    if WEAK_ONLY.match(low.strip()):
        return "unrated", "the only evidence is an absence, which cannot carry a recommendation", False

    # A classifier reading of a short note may flag a researched recommendation
    # for review. It may never convict it. Escalating a published good straight
    # to skip on inferred evidence is the one move with real legal exposure, so
    # the ceiling is unrated and a person looks at it.
    adverse = [k for k in FRONTS if st[k] in ("fail", "caution")]
    if adverse:
        return "unrated", f"the note reads adversely on {', '.join(adverse)}, needs a human look", False

    passes = [k for k in FRONTS if st[k] == "pass"]
    if strict and len(passes) < 4:
        missing = [k for k in FRONTS if st[k] != "pass"]
        return "unrated", f"not assessed on {', '.join(missing)}", False
    if not passes:
        return "unrated", "no front is directly evidenced by the note", False
    if not lenient:
        # A third-party lab measured the product itself, for the hazard class
        # that matters, and reported a limit. Section 4.2 ranks that above a
        # brand's own disclosure and far above a label read, so it stands alone.
        # Requiring a second front on top of it would invert the hierarchy: two
        # things read off a label would qualify where an independent measurement
        # did not.
        if "testing" in passes and scope in ("sku", "line"):
            return "good", f"independent lab result at {scope} scope", False
        if "formula" not in passes:
            return "unrated", "no direct pass on formula, and no lab result standing in for one", False
        # A durable good's material is its whole composition, so formula alone
        # carries it. A consumable needs a second front, because its formula is
        # a recipe and its packaging is a separate object that can migrate.
        if len(passes) < 2 and consumable:
            return "unrated", "consumable with only a formula read, no second front", False
    return "good", f"direct evidence at {scope} scope on {', '.join(passes)}", False


# ------------------------------------------------------------------------ main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true",
                    help="good requires all four fronts to pass")
    ap.add_argument("--lenient", action="store_true",
                    help="good requires any one directly evidenced front")
    ap.add_argument("--show", help="list every row whose verdict becomes this")
    ap.add_argument("--json", help="write the full per-row result here")
    args = ap.parse_args()

    brands = json.loads(DATA.read_text())
    out = []
    change = collections.Counter()
    rules = collections.Counter()
    dead = 0

    for b in brands:
        for p in (b.get("products") or []):
            scope, basis = scope_of(p), basis_of(p)
            raw, authored = fronts_for(p, b)
            f, fired = apply_rules(raw, clean_note(p.get("note")), scope, basis)
            new, why, disclose = correct(p.get("verdict"), f, p.get("note"),
                                         scope, basis, args.strict, args.lenient,
                                         is_consumable(b.get("category"), p.get("name")))
            # A hand-authored scorecard outranks anything inferred from prose.
            if authored:
                new, why, disclose = p.get("verdict"), "hand authored scorecard, left alone", False
            old = p.get("verdict")
            if scope == "none":
                dead += 1
            for r in fired:
                rules[r] += 1
            change[(old, new)] += 1
            out.append({
                "brand": b["brand"], "product": p.get("name"), "asins": p.get("asins"),
                "origin": p.get("origin"), "scope": scope, "basis": basis,
                "category": b.get("category"),
                "consumable": is_consumable(b.get("category"), p.get("name")),
                "old": old, "new": new, "why": why, "fires": fired,
                "fronts": {k: f[k]["status"] for k in FRONTS},
                "needs_scope_disclosure": disclose,
                "fires_in_extension": scope != "none",
            })

    total = len(out)
    moved = sum(v for (o, n), v in change.items() if o != n)
    print(f"audited {total} product rows against docs/rating-rules.md")
    mode = ("strict, good needs all four fronts" if args.strict
            else "lenient, good needs any one direct front" if args.lenient
            else "rules default, good needs a direct formula pass plus one other")
    print(f"mode: {mode}")
    print(f"unchanged {total - moved}   changed {moved}\n")

    print("verdict changes")
    for (o, n), v in sorted(change.items(), key=lambda kv: -kv[1]):
        if o == n:
            continue
        print(f"  {str(o):<8} -> {n:<8} {v:>4}")

    print("\nfinal distribution")
    fin = collections.Counter(r["new"] for r in out)
    for k, v in fin.most_common():
        print(f"  {str(k):<8} {v:>4}")

    print("\nrules fired")
    for k, v in rules.most_common():
        print(f"  {k:<46} {v:>4}")

    print(f"\nrows that never fire in the extension (no ASIN, no match): {dead}")
    nd = sum(1 for r in out if r["needs_scope_disclosure"])
    print(f"adverse rows resting on inherited evidence, copy must name the scope: {nd}")

    by_basis = collections.Counter((r["basis"], r["new"]) for r in out)
    print("\nbasis x new verdict")
    for k, v in sorted(by_basis.items()):
        print(f"  {k[0]:<10} {k[1]:<8} {v:>4}")

    if args.show:
        print(f"\nrows becoming {args.show}:")
        for r in out:
            if r["new"] == args.show and r["old"] != r["new"]:
                print(f"  [{r['brand']}] {r['product']}  ({r['old']} -> {r['new']}) {r['why']}")

    if args.json:
        pathlib.Path(args.json).write_text(json.dumps(out, indent=2, ensure_ascii=False))
        print(f"\nwrote {args.json}")


if __name__ == "__main__":
    sys.exit(main())
