#!/usr/bin/env python3
"""
Audit every product row in brand-data.json against docs/rating-rules.md.

This is the extension's standard, not Brand Check's. The extension speaks about
one product at a time, on a listing page, at the moment of purchase, so it is
held to the strict rule: a recommendation needs direct evidence about the thing
being looked at. Brand Check keeps its brand level view and rolls product rows up
instead. See tools/brand-rollup.py for that half.

What it checks, in the order the rules document sets them out:

  1.1  favourable evidence never propagates, so an inherited row cannot be good
  2    an unobtainable ingredient list is a caution, not an unknown
  4.3  a non detect without a limit of detection cannot be cited as a pass
  5.1  a filed but unresolved suit caps at careful, only a resolution reaches skip
  5.2  a closed and remedied recall over 24 months old is informational
  5.3  absence of a recall is not a pass, and can never be the reason for a good
  6    aggregation, and the direct evidence requirement for good

Reports only. Writing is tools/apply-product-rules.py, so a bad classification
run can never silently rewrite published verdicts.

    python3 tools/audit-product-rules.py
    python3 tools/audit-product-rules.py --strict     # good needs all four fronts
    python3 tools/audit-product-rules.py --show skip  # list every row of one change
    python3 tools/audit-product-rules.py --json out.json
"""

import argparse
import collections
import datetime
import importlib.util
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "brand-data.json"
FRONTS = ("formula", "packaging", "legal", "testing")
# The real date, not a frozen one. Recall decay under rule 5.2 is computed
# against this; pinning it to the day the tool was written meant a recall
# could never age past the threshold no matter how many years went by.
TODAY = datetime.date.today()

# Reuse the classifier rather than growing a second, divergent copy of it.
_spec = importlib.util.spec_from_file_location(
    "backfill_fronts", ROOT / "tools" / "backfill-fronts.py")
_bf = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_bf)


# ---------------------------------------------------------------- scope, basis

def scope_of(prod):
    """
    Which scope the row's evidence actually covers.

    An ASIN list is a claim about those exact listings. A `match` phrase is a
    named product line, written by hand during research. A `matchAll` group is
    brand words plus a category word, which is a brand level claim narrowed to a
    category, and that is the broadest thing the extension is allowed to show.
    """
    if prod.get("asins"):
        return "sku"
    if prod.get("match"):
        return "line"
    if prod.get("matchAll"):
        # Provenance decides, not the field. brand-lines.py generates groups of
        # brand words plus one category word, which really is a brand level claim
        # narrowed to a category. Every other matchAll names a specific product
        # ("earth mama organic diaper balm", "dyson v15 detect"), which is a
        # product line. Reading them all as brand scope silently demoted 36
        # hand-researched recommendations to "we have not reviewed this".
        return "brand" if prod.get("origin") == "brand-line" else "line"
    return "none"


def basis_of(prod):
    # brand-line rows are generated by projecting a brand verdict onto a
    # category. Everything else was written against a specific product.
    return "inherited" if prod.get("origin") == "brand-line" else "direct"


# ----------------------------------------------------------------- front rules

NO_RECALL = re.compile(
    r"\bno (cpsc |fda )?(recall|recalls|lawsuit|lawsuits|class action|filed|"
    r"open recall|reported)\b|\b(closed|ended) without\b|\bnone found\b")
FILED_ONLY = re.compile(r"\b(filed|pending|alleges|alleging|allegation|"
                        r"proposed class|complaint)\b")
RESOLVED = re.compile(r"\b(settled|settlement|judgment|judgement|consent decree|"
                      r"fined|penalty|verdict|ruled|injunction|recalled|recall)\b")
NON_DETECT = re.compile(r"\bnon[\s-]?detect\w*|\bnot detected\b|\bbelow detection\b|"
                        r"\bno lead detected\b|\bundetected\b")
HAS_LOD = re.compile(r"\b(lod|limit of detection|detection limit)\b|"
                     r"\b\d+(\.\d+)?\s?(ppb|ppm|µg|ug|mg)/?\w*\b")
AB1200_ONLY = re.compile(r"\bab ?1200\b")
NO_INGREDIENTS = re.compile(
    r"\b(does not (publish|disclose)|undisclosed|not disclosed|proprietary blend|"
    r"no ingredient list|does not list)\b")
RECALL_YEAR = re.compile(r"\b(19|20)\d{2}\b")


# Store and registry notes carry two kinds of text that are not claims about the
# product: a trailing caveat list, and contrast clauses naming the bad thing this
# product replaces. Classified raw, "a direct swap for the nylon pouf, which
# sheds microplastics" reads as a loofah that sheds microplastics, and
# "Skip bamboo rayon swaddles" reads as an organic cotton swaddle made of rayon.
# Both produced a skip on a researched recommendation, which is the exact
# trade-libel shape the classifier is written to avoid.
CAVEAT = re.compile(r"\bworth knowing\s*:.*$", re.I | re.S)
CONTRAST_CLAUSE = re.compile(
    r"(?:^|(?<=[.;,]))\s*(?:skip|avoid|unlike|instead of|rather than|compared to|"
    r"as opposed to|not like|a (?:direct )?(?:swap|replacement|alternative) for)\b[^.;]*",
    re.I)


# Ways the copy mentions plastic without the product containing any. A steel
# purifier "rather than plastic", a glass jar that "skips the multilayer plastic
# concern", a shell that "never touches the milk", a weight "close to a plastic
# bottle's", and "plastic neutral certified", which is a carbon offset claim and
# not a material at all. All five were scoring as plastic contact.
NOT_CONTACT = re.compile(
    r"\b(?:rather than|instead of|not|no|never|without|avoids?|skips?|replaces?|"
    r"unlike|versus|vs\.?|compared (?:to|with)|as (?:light|heavy) as|close to)\s+"
    r"(?:the\s+|a\s+|an\s+|any\s+)?[\w\s-]{0,24}?plastic\w*[^.;]*"
    r"|plastic\w*[\s-]+(?:neutral|negative|free|offset)"
    r"|\bnever touches\b[^.;]*"
    r"|\bdoes not (?:touch|contact)\b[^.;]*", re.I)

# A source's name is provenance, not a finding. "Lead Safe Mama" put the word
# lead into every note citing them, which cancelled out the very non-detect they
# had published: Weleda Salt Toothpaste, a non detect at a 5 ppb limit, scored
# one hazard against one clean result and came out neutral.
# Only names that contain a hazard word need masking, and only one does. Masking
# the rest cost real signal: MADE SAFE is a certification the classifier scores
# as a testing pass, and it was being replaced with the word "lab".
SOURCE_NAMES = re.compile(r"\blead safe mama\b", re.I)


def clean_note(note):
    """Strip caveats, contrast clauses and source names so only claims remain."""
    n = CAVEAT.sub("", note or "")
    n = CONTRAST_CLAUSE.sub(" ", n)
    n = SOURCE_NAMES.sub("the lab", n)
    n = NOT_CONTACT.sub(" ", n)
    return re.sub(r"\s+", " ", n).strip()


def evidence_text(prod):
    """
    Everything the classifier may read about this row: the display note plus
    the `research` field.

    Research lives in its own field on purpose. The first materials sweep
    appended its facts to the note, and the next build silently deleted 77 of
    121 of them, because store-to-products refreshes store row notes from the
    store data on every run. A field no note-refreshing tool knows about is
    the only text guaranteed to survive the pipeline.

    Cleaned part by part, never as one string: the caveat stripper cuts from
    "Worth knowing:" to the end of its text, and text joined after a note
    that ends in a caveat would be amputated along with it.
    """
    return f"{clean_note(prod.get('note'))} {clean_note(prod.get('research'))}".strip()


MATERIALS_SEG = re.compile(r"\bMaterials:\s*(.+?)(?=\s+Packaging:|$)", re.S)


def formula_evidence(prod):
    """
    Just the formula portion of the research, for the formula read.

    The materials read scans the whole text for hazards, which is right for a
    durable good and wrong for a labelled research field: "creatine powder in
    a plastic tub" vetoed a single ingredient formula pass on the word
    plastic, which describes the tub the packaging front already judged.
    """
    segs = MATERIALS_SEG.findall(prod.get("research") or "")
    return clean_note(" ".join(segs))


# The classifier was written for brand prose, where a claim comes wrapped in
# argument. Store and registry notes are spec sheets: "18/8 stainless", "100%
# cotton muslin", "medical grade borosilicate glass". Those name the material
# outright and carry no argument for the polarity test to grip, so the formula
# front came back unknown on rows whose formula is the most certain thing about
# them. Naming an inert material with no hazard term anywhere in the note is a
# formula pass, and that is all rule 2 ever asked for.
INERT = [
    "stainless", "18/8", "18/10", "304 steel", "316 steel", "borosilicate",
    "tempered glass", "glass", "cast iron", "carbon steel", "enamel", "enameled",
    "organic cotton", "cotton", "muslin", "linen", "hemp", "wool", "merino",
    "silk", "tencel", "lyocell", "jute", "sisal", "loofah", "plant fiber",
    "plant fibre", "solid wood", "maple", "beech", "birch", "bamboo fiber",
    "beeswax", "paper", "unbleached", "food grade silicone", "platinum silicone",
    "wood pulp", "pulp", "cellulose", "fsc", "viscose free", "tencel",
    "wood", "wooden", "olive wood", "acacia", "walnut", "teak", "cherry wood",
    "hardwood", "end grain", "granite", "marble", "soapstone", "slate",
    "tampico", "horsehair", "boar bristle", "mesh", "wire",
    "bamboo", "rattan", "coconut", "loofa", "seagrass", "rubberwood",
    "titanium", "copper", "brass", "porcelain", "stoneware", "cork",
    "natural rubber", "latex free", "aluminium free", "aluminum free",
    # "clay" is deliberately absent. Fired pottery is covered by ceramic,
    # porcelain and stoneware; raw clay in a consumable is the standard's own
    # example of an ingredient borne heavy metal carrier (section 4), and
    # Earthpaste measured 3,500 ppb lead riding in on exactly that. A word
    # that names the hazard class cannot also read as an inert material.
]
# Section 2.1. Two kinds of entry, which behave differently.
#
# A named hazard is a specific substance with evidence behind it. Un-negated, in
# the path that reaches a person, it fails the front on its own.
HAZARD = [
    "plastic", "polyester", "nylon", "acrylic", "spandex", "elastane",
    "ptfe", "teflon", "nonstick", "non-stick", "pfoa", "pfas", "pvc",
    "polycarbonate", "polypropylene", "polyethylene", "polystyrene", "styrene",
    "melamine", "viscose", "rayon", "neoprene", "phthalate", "paraben",
    "formaldehyde", "triclosan", "flame retardant",
    "bpa", "bps", "bpf", "lead", "cadmium", "azo", "chemical filter",
    # The substances the published research actually judged on, by name, so an
    # ingredient list can be scanned the way a person read it. Chemical UV
    # filters (the sunscreen standard), the individual parabens and
    # formaldehyde releasers a label would use, the aluminum salts that make
    # an antiperspirant (never bare "aluminum", which also names an inert
    # container), and talc.
    "oxybenzone", "avobenzone", "octinoxate", "octisalate", "octocrylene",
    "homosalate", "chemical sunscreen",
    "methylparaben", "propylparaben", "butylparaben", "ethylparaben",
    "isobutylparaben",
    "dmdm hydantoin", "quaternium-15", "imidazolidinyl urea",
    "diazolidinyl urea", "bronopol",
    "aluminum chlorohydrate", "aluminium chlorohydrate",
    "aluminum zirconium", "aluminium zirconium",
    "talc", "benzene",
]

# A disclosure failure is a legal umbrella that hides composition. It names no
# harmful substance; it says we cannot check. So it caps at caution and never
# fails a front alone. We count concealment, which the maker chose, and not the
# absence of independent testing, which they did not. Keeping "fragrance" in the
# list above would have failed a product on a word that means "undisclosed".
DISCLOSURE_FAILURE = [
    "fragrance", "parfum", "gum base", "proprietary blend", "natural flavors",
    "natural flavour", "artificial flavors", "undisclosed",
]


# For a durable good the object IS its material, so formula and packaging are one
# front and a fully specified inert material is the complete safety case. A
# stainless bowl with no coating has nothing further to disclose, and demanding a
# lab result before recommending one is not a standard, it is a blocker.
#
# For a consumable the two come apart. The formula is a recipe, the packaging is
# a separate object that can migrate into it, and lab testing routinely finds
# what the ingredient list cannot show. There the second front is real, so the
# rules default applies unchanged.
CONSUMABLE_WORDS = (
    "cosmetic", "personal care", "sunscreen", "skincare", "supplement",
    "bottled water", "food", "formula", "electrolyte", "oral care", "cleaning",
    "laundry", "coffee bean", "salt", "diaper cream", "diaper", "wipe",
    "period", "deodorant", "toothpaste", "spice", "protein", "pantry",
)
DURABLE_OVERRIDE = ("cloth diaper", "diaper bag", "diaper pail", "food storage",
                    "baby food storage", "food prep")


def is_consumable(category, product_name=""):
    # The override reads the product name too: a brand can sit in a consumable
    # category ("Diapers & wipes") while the row names a durable object
    # ("diaper pail"). The name only ever argues one way, towards durable,
    # so it can never turn a genuinely consumable row into one that skips
    # the second front requirement.
    cat = (category or "").lower()
    name = (product_name or "").lower()
    if any(w in cat or w in name for w in DURABLE_OVERRIDE):
        return False
    return any(w in cat for w in CONSUMABLE_WORDS)


# --------------------------------------------------------- packaging severity
#
# Plastic contact is not a verdict. If it were, we would skip nearly every
# cosmetic, supplement and cleaning product on the market, and the flag would
# stop carrying information precisely because it fires on everything.
#
# What actually governs migration is the pairing: how aggressively the contents
# extract, against what the polymer has to give. A water based toner in PET and
# a cleansing balm in the same bottle are not the same exposure, because almost
# everything that leaches out of a plastic is lipophilic. Oil pulls it, water
# largely does not.
#
# So packaging fails only where an extracting formula meets a polymer with
# something to give.

# How hard the contents pull on the container, lowest first.
EXTRACTION = [
    (0, "dry", r"\b(powder|tablet|capsule|bar soap|shampoo bar|dry|granule|"
               r"pastille|lozenge|sachet of powder|loose leaf)\b"),
    (1, "aqueous", r"\b(water based|aqueous|hydrosol|toner|mist|essence|"
                   r"micellar|gel|hydrating|99% water|water\b)"),
    (2, "surfactant", r"\b(shampoo|body wash|face wash|cleanser|detergent|"
                      r"dish soap|foaming|surfactant|castile|bubble bath)\b"),
    (2, "alcohol", r"\b(alcohol|ethanol|denat|witch hazel|astringent|spray|"
                   r"sanitiser|sanitizer|perfume|fragrance mist)\b"),
    (2, "acidic", r"\b(vitamin c|ascorbic|glycolic|salicylic|lactic acid|aha|bha|"
                  r"vinegar|citric|low ph|exfoliating acid)\b"),
    (3, "emulsion", r"\b(lotion|cream|moisturis|moisturiz|emulsion|conditioner|"
                    r"balm cream|milk\b|butter blend)\b"),
    (4, "anhydrous", r"\b(oil|balm|butter|salve|ointment|serum oil|cleansing balm|"
                     r"lip balm|body oil|face oil|anhydrous|petrolatum|wax)\b"),
]
# What the polymer has to give up.
POLYMER = [
    (0, "inert", r"\b(glass|stainless|steel|aluminium free|tin\b|foil lined|"
                 r"borosilicate|ceramic|porcelain)\b"),
    (1, "polyolefin", r"\b(hdpe|ldpe|polyethylene|polypropylene|\bpp\b|#2\b|#5\b|"
                      r"#4\b|food grade silicone|platinum silicone)\b"),
    (2, "pet", r"\b(pet\b|pete\b|polyester bottle|#1\b|tritan|copolyester)\b"),
    # Resins only. BPA and phthalates are additives, not containers, and in our
    # notes they appear either as a claim the product avoids them or as a lab
    # result, which is the testing front's business. Reading them as a polymer
    # failed Bobbie infant formula on the strength of "tested non detect for
    # lead, arsenic, cadmium, mercury, BPA".
    (3, "leachy", r"\b(pvc|polycarbonate|polystyrene|styrene|#3\b|#6\b|#7\b|"
                  r"melamine)\b"),
]
# How much of what migrates actually reaches a person. A laundry detergent and a
# face oil can sit in the same bottle and extract the same compounds, and then
# one is diluted ten thousand fold and rinsed down a drain while the other is
# spread on skin and left there. Reading only the container treats those as the
# same finding, which is how a perfectly ordinary detergent jug ends up cautioned.
RINSE_OFF = re.compile(r"\b(shampoo|conditioner|body wash|face wash|cleanser|"
                       r"hand soap|bar soap|castile|bubble bath|toothpaste|"
                       r"mouthwash|exfoliant|mask)\b", re.I)
NOT_ON_BODY = re.compile(r"\b(laundry|detergent|dish soap|dishwasher|all purpose|"
                         r"all-purpose|surface|floor|glass cleaner|bathroom cleaner|"
                         r"stain remover|softener|degreaser)\b", re.I)

HEATED = re.compile(r"\b(hot fill|hot-fill|microwav\w*|boil\w*|steril\w*|"
                    r"dishwasher|heat\w*|hot water|hot liquid|shower)\b", re.I)
GENERIC_PLASTIC = re.compile(r"\bplastic\w*\b", re.I)


def packaging_severity(note, context=""):
    """
    Return (status, why) for the packaging front, or (None, None) when the note
    says nothing about a container.

    The matrix, contents down the side and polymer across:

                    inert   polyolefin   PET    PVC/PC/PS
        dry          pass      pass      pass    caution
        aqueous      pass      pass      pass    caution
        surfactant   pass      pass    caution   caution
        alcohol      pass      pass    caution      fail
        acidic       pass      pass    caution      fail
        emulsion     pass    caution   caution      fail
        anhydrous    pass    caution     fail       fail

    Heat moves anything in a plastic one step worse, because temperature drives
    migration harder than any other single variable.
    """
    low = " " + (note or "").lower() + " "
    # The exposure route is usually stated in the product name and the category
    # rather than in the note. "Baby Liquid Laundry Detergent" says everything
    # about how much of the bottle reaches a person; the note only said "liquid
    # in a 50 ounce plastic bottle" and drew a caution for it.
    route = low + " " + (context or "").lower() + " "

    def present(pat):
        """A term the copy rules out is not a term the product contains."""
        for m in re.finditer(pat, low, re.I):
            if not _bf.is_negated(low, m.start(), m.end()):
                return True
        return False

    poly, poly_name = None, None
    for rank, name, pat in POLYMER:
        if present(pat):
            if poly is None or rank > poly:
                poly, poly_name = rank, name
    # An unqualified "plastic" with no resin named. Treat as PET, the commonest
    # bottle and the middle of the range, rather than guessing best or worst.
    # Taken as a maximum, not as a fallback: a glass jar with a plastic lid is a
    # plastic contact layer, and reading only the glass missed every one of them.
    if present(GENERIC_PLASTIC.pattern) and (poly is None or poly < 2):
        poly, poly_name = 2, "unspecified plastic"
    if poly is None or poly == 0:
        return None, None

    pull, pull_name = None, None
    for rank, name, pat in EXTRACTION:
        if present(pat) and (pull is None or rank > pull):
            pull, pull_name = rank, name
    # Nothing in the note describes what is inside. Defaulting to dry was a
    # false pass, and defaulting to oil would be a libel: a polypropylene baby
    # bottle scored "dry contents" and passed, when the contents are warm milk.
    # Where the contents are unknown we can only speak about the polymer, and
    # only the genuinely leachy resins say anything on their own.
    if pull is None:
        return ("caution", f"{poly_name}, contents not described") if poly >= 3 else (None, None)

    grid = {
        (0, 1): "pass", (0, 2): "pass", (0, 3): "caution",
        (1, 1): "pass", (1, 2): "pass", (1, 3): "caution",
        (2, 1): "pass", (2, 2): "caution", (2, 3): "fail",
        (3, 1): "caution", (3, 2): "caution", (3, 3): "fail",
        (4, 1): "caution", (4, 2): "fail", (4, 3): "fail",
    }
    status = grid.get((pull, poly), "caution")
    note_bits = [f"{pull_name} contents in {poly_name}"]
    if HEATED.search(low):
        status = {"pass": "caution", "caution": "fail", "fail": "fail"}[status]
        note_bits.append("heated in use")
    # Relief for what never stays on a person. One step for a rinse-off, two for
    # something that only ever touches laundry or a worktop.
    softer = {"fail": "caution", "caution": "pass", "pass": "pass"}
    if NOT_ON_BODY.search(route):
        status = softer[softer[status]]
        note_bits.append("diluted and rinsed, never left on skin")
    elif RINSE_OFF.search(route):
        status = softer[status]
        note_bits.append("rinsed off")
    return status, ", ".join(note_bits)


# A complete list of one. "Single ingredient: creatine monohydrate" is a full
# disclosure by definition, and one named ingredient either trips the hazard
# scan or it does not.
SINGLE_INGREDIENT = re.compile(
    r"\b(?:single|sole|only|one)[\s-]+(?:active[\s-]+)?ingredient\b", re.I)
# A list recorded AS the list. Section 2's formula verdict is mechanical once
# the full list is on the table: nothing on the hazard list is a pass, a
# disclosure umbrella caps at caution, a named hazard fails. What the engine
# must not do is treat a prose summary ("an aloe base with oils and extracts")
# as complete, so the pass fires only where the text claims to BE the list.
FULL_LIST = re.compile(
    r"\b(?:full|complete)\s+ingredient\s+list\b|\b(?:ingredients|inci)\s*:", re.I)


def formula_from_materials(note):
    """
    ('pass', why) when the note names an inert material or a single disclosed
    ingredient and no hazard; ('caution', why) on a disclosure failure;
    (None, None) otherwise.

    Hazard words that the copy explicitly rules out do not count, so
    "no interior coating", "BPA free cap" and "phthalate free" stay passes.
    """
    low = " " + (note or "").lower() + " "
    for h in HAZARD:
        for m in re.finditer(r"(?<![a-z0-9])" + re.escape(h) + r"(?![a-z0-9])", low):
            if not _bf.is_negated(low, m.start(), m.end()):
                return None, None
    # A disclosure failure is not a clean read either. It is the state where the
    # maker has not told us, which section 2.1 caps at caution.
    for t in DISCLOSURE_FAILURE:
        for m in re.finditer(r"(?<![a-z0-9])" + re.escape(t) + r"(?![a-z0-9])", low):
            if not _bf.is_negated(low, m.start(), m.end()):
                return "caution", "Carries an undisclosed mixture, so the formula cannot be checked."
    if any(_bf.has(low, t) for t in INERT):
        return "pass", "Materials named in the listing."
    if SINGLE_INGREDIENT.search(low):
        return "pass", "A single disclosed ingredient, with nothing on the hazard list."
    if FULL_LIST.search(low):
        return "pass", "Full ingredient list published, with nothing on the hazard list."
    return None, None


def fronts_for(prod, brand):
    """Classify the row's own note. Never falls back to the brand's prose."""
    if prod.get("fronts") and prod["fronts"].get("authored"):
        return {f: prod["fronts"][f] for f in FRONTS if f in prod["fronts"]}, True
    pseudo = {"reason": evidence_text(prod), "evidence": "", "stance": None}
    return _bf.build_fronts(pseudo), False


def apply_rules(fronts, note, scope, basis, context="", formula_text=""):
    """
    Fold the rules document's per-front corrections into a classified scorecard.
    Returns the corrected fronts plus the list of rules that fired.
    """
    low = (note or "").lower()
    fired = []
    f = {k: dict(v) for k, v in fronts.items()}

    # 5.3  absence of a recall is not a pass. Barely regulated categories produce
    #      no recalls because nobody is looking, not because nothing is wrong.
    if f["legal"]["status"] == "pass" and NO_RECALL.search(low) and not RESOLVED.search(low):
        f["legal"] = {"status": "unassessed", "note": "Checked, nothing found.",
                      "origin": "rule-5.3"}
        fired.append("5.3 no-recall-is-not-a-pass")

    # 5.1  a filed suit is an allegation. Only a resolution can fail the front.
    if f["legal"]["status"] == "fail" and FILED_ONLY.search(low) and not RESOLVED.search(low):
        f["legal"]["status"] = "caution"
        fired.append("5.1 filed-suit-caps-at-caution")

    # 5.2  a closed, remedied recall older than 24 months is informational.
    # Notes carry a year, not a date, so the cutoff is three calendar years
    # back: the only threshold that PROVES the recall is older than 24 months.
    # A recall from two years back may be 20 or 32 months old, and when we
    # cannot tell, it stays active. Conservative by construction.
    if f["legal"]["status"] in ("fail", "caution") and "recall" in low:
        years = [int(y) for y in RECALL_YEAR.findall(low)]
        if years and max(years) <= TODAY.year - 3 and re.search(
                r"\b(closed|remedied|resolved|fixed|corrected|since)\b", low):
            f["legal"] = {"status": "unassessed",
                          "note": f["legal"].get("note", ""), "origin": "rule-5.2"}
            fired.append("5.2 recall-decayed")

    # 4.3  a non detect is not comparable, and not citable, without its limit.
    if f["testing"]["status"] == "pass" and NON_DETECT.search(low) and not HAS_LOD.search(low):
        f["testing"]["status"] = "unassessed"
        fired.append("4.3 non-detect-without-lod")

    # 4.3 stated positively. A non detect reported WITH its limit is exactly what
    # the rule asks for and is citable as a pass. The classifier could not see
    # this: it knows "non-detect" hyphenated but not "non detect" spaced, and it
    # holds no positive term for a clean result at a stated limit at all. Weleda
    # Salt Toothpaste, a non detect at 5 ppb and one of three pastes in the guide
    # to clear the line, scored nothing on the only front it has evidence for.
    if (f["testing"]["status"] in ("unknown", "unassessed")
            and NON_DETECT.search(low) and HAS_LOD.search(low)):
        f["testing"] = {"status": "pass",
                        "note": "Non detect at a stated limit of detection.",
                        "origin": "rule-4.3"}
        fired.append("4.3 non-detect-with-lod-is-a-pass")

    # 5.3 again, on the formula front. An AB 1200 disclosure existing is a legal
    #     front nothing. It is not evidence about what is in the pan.
    if f["formula"]["status"] == "pass" and AB1200_ONLY.search(low):
        strong = re.search(r"\bdiscloses no\b|\bno intentionally added\b", low)
        if not strong:
            f["formula"]["status"] = "unassessed"
            fired.append("5.3 ab1200-disclosure-is-not-a-formula-pass")

    # 2  an ingredient list we cannot obtain is a finding, not an absence of one.
    if f["formula"]["status"] in ("unknown", "unassessed") and NO_INGREDIENTS.search(low):
        f["formula"] = {"status": "caution",
                        "note": "The manufacturer does not publish a complete ingredient list.",
                        "origin": "rule-2"}
        fired.append("2 non-disclosure-is-a-caution")

    # Rule 3: the packaging front is decided by the pairing, not by the word
    # plastic appearing. This overrides the keyword classifier outright, because
    # the classifier can only see whether a hazard word is present and the whole
    # question is what that hazard is sitting next to.
    pk, pk_why = packaging_severity(note, context)
    if pk:
        f["packaging"] = {"status": pk, "note": pk_why.capitalize() + ".",
                          "origin": "rule-3-matrix"}
        fired.append(f"3 packaging-matrix-{pk}")

    # Packaging stated as plastic free. A solid bar in compostable cardboard or a
    # refillable aluminium bottle answers the packaging question outright, and
    # the classifier had no term for it, so shampoo bars whose whole point is the
    # packaging scored nothing on that front.
    if f["packaging"]["status"] in ("unknown", "unassessed") and re.search(
            r"\b(compostable (cardboard|paper|packaging)|cardboard (box|packaging|carton)|"
            r"(refillable|reusable) (aluminium|aluminum|steel|glass)|plastic[- ]free packaging|"
            r"no plastic packaging|paper wrap|zero waste packaging|package[- ]free)\b", low):
        f["packaging"] = {"status": "pass",
                          "note": "Packaging is stated as plastic free.",
                          "origin": "rule-3-plastic-free-packaging"}
        fired.append("3 packaging-stated-plastic-free")

    # Rule 2: formula is always resolvable, so read the material directly when
    # the classifier's polarity test found nothing to grip on.
    if f["formula"]["status"] in ("unknown", "unassessed"):
        # Read the product name too. "Forlife Stainless Steel Tea Infuser" and
        # "Scanwood Olive Wood Cooking Spoon" name the material in the title and
        # never repeat it in the note, so reading the note alone found nothing.
        read, read_why = formula_from_materials(note + " " + (context or ""))
        # The whole-text read is vetoed by any hazard word, including one that
        # only describes the container. Where labelled formula evidence exists,
        # judge it on its own.
        if read is None and formula_text:
            read, read_why = formula_from_materials(formula_text)
        if read == "pass":
            f["formula"] = {"status": "pass", "note": read_why,
                            "origin": "rule-2-materials"}
            fired.append("2 formula-read-from-materials")
        elif read == "caution":
            f["formula"] = {"status": "caution", "note": read_why,
                            "origin": "rule-2.1-disclosure"}
            fired.append("2.1 disclosure-failure-caps-at-caution")

    # Rule 5.4. A durable good is its own contact surface: a stainless bowl's
    # "packaging" is the stainless. Where the material reads clean and nothing
    # contradicts it, the packaging front is answered by the same fact rather
    # than left blank next to a recommendation.
    if (not is_consumable(context) and f["formula"]["status"] == "pass"
            and f["packaging"]["status"] in ("unknown", "unassessed")
            and not GENERIC_PLASTIC.search(low)):
        f["packaging"] = {"status": "pass",
                          "note": "The object is its own contact surface, and the material reads clean.",
                          "origin": "rule-5.4"}
        fired.append("5.4 durable-good-is-its-own-packaging")

    # normalise the classifier's "unknown" to the rules document's vocabulary
    for k in f:
        if f[k].get("status") == "unknown":
            f[k]["status"] = "unassessed"
    return f, fired


WEAK_ONLY = re.compile(
    r"^(?:[^.]*\b(?:no (?:cpsc |fda )?recall|no (?:filed|open) |none found|"
    r"ab ?1200|discloses|non[\s-]?detect)\b[^.]*[.]?\s*)+$")


def correct(old, f, note, scope, basis, strict=False, lenient=False, consumable=True,
            origin=None):
    """
    Section 6, applied as a correction rather than a re-adjudication.

    The verdict already on the row was written by a person, either directly or
    in a ranked article table. That judgement is evidence and the rules do not
    discard it. What the rules govern is whether it is allowed to travel, and
    whether the evidence under a recommendation is strong enough to carry one.

    Returns (verdict, reason, needs_disclosure).
    """
    low = (note or "").lower()
    st = {k: f[k]["status"] for k in FRONTS}

    # ---- adverse verdicts -------------------------------------------------
    # 1.1 adverse evidence may propagate, so an inherited caution or skip
    # stands. 1.2 requires the copy to name the scope it came from.
    if old in ("careful", "skip"):
        # 5.1 a filed but unresolved suit is an allegation. If that is the only
        # adverse finding on the row, it caps at careful.
        if old == "skip" and FILED_ONLY.search(low) and not RESOLVED.search(low):
            adverse = [k for k in FRONTS if st[k] in ("fail", "caution")]
            if adverse in ([], ["legal"]):
                return "careful", "a filed suit is an allegation, capped at careful", basis != "direct"
        # 5.2 a closed and remedied recall over 24 months old is informational.
        if "recall" in low:
            years = [int(y) for y in RECALL_YEAR.findall(low)]
            remedied = re.search(r"\b(closed|remedied|resolved|fixed|corrected)\b", low)
            if years and remedied and max(years) <= TODAY.year - 3:
                adverse = [k for k in FRONTS if st[k] in ("fail", "caution")]
                if adverse in ([], ["legal"]):
                    return "unrated", f"recall closed and remedied in {max(years)}, now informational", False
        return old, "adverse finding stands", basis != "direct"

    # ---- neutral ----------------------------------------------------------
    # Not a verdict in the rules vocabulary. It asserts nothing, so it renders
    # as the state that asserts nothing.
    if old == "neutral":
        return "unrated", "neutral is not a verdict, nothing is being asserted", False

    # ---- recommendations --------------------------------------------------
    # 1.1 favourable evidence never propagates. This is the whole Sensarte fix.
    if basis != "direct":
        return "unrated", "a recommendation cannot rest on inherited evidence", False
    if scope not in ("sku", "line"):
        return "unrated", f"a recommendation needs sku or line scope, this is {scope}", False

    # 5.3 absence of a recall is not a pass, and an AB 1200 disclosure existing
    # is a legal front nothing. Neither can be the reason something is good.
    # 4.3 a non detect without its limit of detection is not citable either.
    # The one exception is 5.5: a non detect reported WITH its limit is an
    # independent measurement of the product, the strongest evidence we hold,
    # and the weak-evidence regex must not swallow it just because the note
    # says nothing else. A row whose entire note is "non detect at 5 ppb"
    # is exactly the row that rule exists for.
    if WEAK_ONLY.match(low.strip()) and not (NON_DETECT.search(low) and HAS_LOD.search(low)):
        return "unrated", "the only evidence is an absence, which cannot carry a recommendation", False

    # A classifier reading of a short note may flag a researched recommendation
    # for review. It may never convict it. Escalating a published good straight
    # to skip on inferred evidence is the one move with real legal exposure, so
    # the ceiling is unrated and a person looks at it.
    adverse = [k for k in FRONTS if st[k] in ("fail", "caution")]
    if adverse:
        return "unrated", f"the note reads adversely on {', '.join(adverse)}, needs a human look", False

    passes = [k for k in FRONTS if st[k] == "pass"]
    if strict and len(passes) < 4:
        missing = [k for k in FRONTS if st[k] != "pass"]
        return "unrated", f"not assessed on {', '.join(missing)}", False
    if not passes:
        return "unrated", "no front is directly evidenced by the note", False
    # A store listing is not an inference. A person read the product, chose it,
    # and put our name to it, which is direct human judgement at product scope,
    # the exact thing rule 6 asks for. The strict bar exists to stop a BRAND
    # verdict leaking onto a product nobody researched; applying it to our own
    # published picks made the store and the extension disagree about what we
    # recommend, which is worse than either answer alone. The scorecard still
    # shows only the fronts the note actually evidences.
    if origin == "store" and scope in ("sku", "line"):
        return "good", "a vetted store pick, chosen by a person at product scope", False

    if not lenient:
        # A third-party lab measured the product itself, for the hazard class
        # that matters, and reported a limit. Section 4.2 ranks that above a
        # brand's own disclosure and far above a label read, so it stands alone.
        # Requiring a second front on top of it would invert the hierarchy: two
        # things read off a label would qualify where an independent measurement
        # did not.
        if "testing" in passes and scope in ("sku", "line"):
            return "good", f"independent lab result at {scope} scope", False
        if "formula" not in passes:
            return "unrated", "no direct pass on formula, and no lab result standing in for one", False
        # A durable good's material is its whole composition, so formula alone
        # carries it. A consumable needs a second front, because its formula is
        # a recipe and its packaging is a separate object that can migrate.
        if len(passes) < 2 and consumable:
            return "unrated", "consumable with only a formula read, no second front", False
    return "good", f"direct evidence at {scope} scope on {', '.join(passes)}", False


# ------------------------------------------------------------------------ main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true",
                    help="good requires all four fronts to pass")
    ap.add_argument("--lenient", action="store_true",
                    help="good requires any one directly evidenced front")
    ap.add_argument("--show", help="list every row whose verdict becomes this")
    ap.add_argument("--json", help="write the full per-row result here")
    args = ap.parse_args()

    brands = json.loads(DATA.read_text())
    out = []
    change = collections.Counter()
    rules = collections.Counter()
    dead = 0

    for b in brands:
        for p in (b.get("products") or []):
            scope, basis = scope_of(p), basis_of(p)
            raw, authored = fronts_for(p, b)
            # Both steps read the same cleaned text. correct() used to get the
            # raw note, so a caveat list or a contrast clause ("unlike brands
            # facing lawsuits") could flip its suit and recall regexes while
            # being invisible to the fronts step.
            cleaned = evidence_text(p)
            f, fired = apply_rules(raw, cleaned, scope, basis,
                                   f"{p.get('name') or ''} {b.get('category') or ''}",
                                   formula_text=formula_evidence(p))
            new, why, disclose = correct(p.get("verdict"), f, cleaned,
                                         scope, basis, args.strict, args.lenient,
                                         is_consumable(b.get("category"), p.get("name")),
                                         p.get("origin"))
            # A hand-authored scorecard outranks anything inferred from prose.
            if authored:
                new, why, disclose = p.get("verdict"), "hand authored scorecard, left alone", False
            old = p.get("verdict")
            if scope == "none":
                dead += 1
            for r in fired:
                rules[r] += 1
            change[(old, new)] += 1
            out.append({
                "brand": b["brand"], "product": p.get("name"), "asins": p.get("asins"),
                "origin": p.get("origin"), "scope": scope, "basis": basis,
                "category": b.get("category"),
                "consumable": is_consumable(b.get("category"), p.get("name")),
                "old": old, "new": new, "why": why, "fires": fired,
                "fronts": {k: f[k]["status"] for k in FRONTS},
                "needs_scope_disclosure": disclose,
                "fires_in_extension": scope != "none",
            })

    total = len(out)
    moved = sum(v for (o, n), v in change.items() if o != n)
    print(f"audited {total} product rows against docs/rating-rules.md")
    mode = ("strict, good needs all four fronts" if args.strict
            else "lenient, good needs any one direct front" if args.lenient
            else "rules default, good needs a direct formula pass plus one other")
    print(f"mode: {mode}")
    print(f"unchanged {total - moved}   changed {moved}\n")

    print("verdict changes")
    for (o, n), v in sorted(change.items(), key=lambda kv: -kv[1]):
        if o == n:
            continue
        print(f"  {str(o):<8} -> {n:<8} {v:>4}")

    print("\nfinal distribution")
    fin = collections.Counter(r["new"] for r in out)
    for k, v in fin.most_common():
        print(f"  {str(k):<8} {v:>4}")

    print("\nrules fired")
    for k, v in rules.most_common():
        print(f"  {k:<46} {v:>4}")

    print(f"\nrows that never fire in the extension (no ASIN, no match): {dead}")
    nd = sum(1 for r in out if r["needs_scope_disclosure"])
    print(f"adverse rows resting on inherited evidence, copy must name the scope: {nd}")

    by_basis = collections.Counter((r["basis"], r["new"]) for r in out)
    print("\nbasis x new verdict")
    for k, v in sorted(by_basis.items()):
        print(f"  {k[0]:<10} {k[1]:<8} {v:>4}")

    if args.show:
        print(f"\nrows becoming {args.show}:")
        for r in out:
            if r["new"] == args.show and r["old"] != r["new"]:
                print(f"  [{r['brand']}] {r['product']}  ({r['old']} -> {r['new']}) {r['why']}")

    if args.json:
        pathlib.Path(args.json).write_text(json.dumps(out, indent=2, ensure_ascii=False))
        print(f"\nwrote {args.json}")


if __name__ == "__main__":
    sys.exit(main())
