#!/usr/bin/env python3
"""
Roll product verdicts up into the brand stance for Brand Check.

The two surfaces answer different questions and are deliberately not the same
system:

  Extension    "is THIS product safe?"  Strict, per product, no inheritance.
                A recommendation needs direct evidence about the exact thing on
                screen. See tools/audit-product-rules.py.

  Brand Check  "what do we make of this brand?"  A brand keeps its own stance
                and lists its products underneath, and the presence of a single
                flagged product is itself a fact about the brand worth showing.

The rollup rule: if any researched product under a brand is careful or skip, the
brand is at least careful. One bad product does not condemn a company, so a skip
product produces a careful brand, not a skip brand. What it means is "the answer
depends which product you pick", which is exactly what the shopper needs to know
before they read a single line further.

Two things are excluded from the rollup:

  brand-line rows, because they are generated by projecting the brand stance
  onto a category. Rolling them back up would be circular, the brand's own
  verdict returning to it dressed as evidence.

  an existing skip brand, which is never softened to careful. The rollup only
  ever tightens.

    python3 tools/brand-rollup.py             # report only
    python3 tools/brand-rollup.py --write
    python3 tools/brand-rollup.py --show      # list every brand that moves
"""

import argparse
import collections
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "brand-data.json"

RANK = {"good": 0, "neutral": 0, "careful": 1, "skip": 2}
VRANK = {"skip": 0, "careful": 1, "neutral": 2, "good": 3}


def shown_verdict(p):
    """The verdict Product Check shows for a product.

    brand-check.html draws the stricter of the verdict typed for a row and the
    one its recorded checks produce (ext.verdict), because Product Check is the
    source of truth and a finding the checks recorded must not hide behind an
    older typed answer. Rolling up the typed field alone left 32 brands at good
    or context over a product the page itself showed as careful or skip. There
    is deliberately no fallback to the brand's own stance here: a brand cannot
    be evidence about itself.
    """
    typed = p.get("verdict")
    ruled = (p.get("ext") or {}).get("verdict")
    if ruled not in VRANK:
        return typed
    if typed not in VRANK:
        return ruled
    return ruled if VRANK[ruled] < VRANK[typed] else typed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--show", action="store_true", help="list every brand that moves")
    ap.add_argument("--fronts-only", action="store_true",
                    help="fill blank brand scorecards from researched product rows "
                         "and touch no stance")
    args = ap.parse_args()

    brands = json.loads(DATA.read_text())

    # The stance rollup below rewrites b["stance"], which is why CLAUDE.md warns
    # that running this file on its own once flipped about sixty unrelated store
    # picks. Filling in a blank scorecard cannot do that: it only ever writes a
    # front that was empty, and it never reads or sets a stance. So the safe
    # half gets its own door, and check.sh walks through that one.
    if args.fronts_only:
        filled, adverse, favourable = roll_fronts(brands)
        print(f"brand scorecard cells filled from researched rows: {filled}"
              f"  ({adverse} adverse, {favourable} favourable)")
        if args.write:
            DATA.write_text(json.dumps(brands, indent=2, ensure_ascii=False) + "\n")
            print(f"wrote {DATA.name}")
        else:
            print("dry run. re-run with --write to apply.")
        return 0
    moved, moves = 0, []
    already = no_products = 0
    reasons = collections.Counter()

    for b in brands:
        rows = b.get("products") or []
        # Only independently researched rows count as evidence about the brand.
        researched = [p for p in rows if p.get("origin") != "brand-line"]
        flagged = [p for p in researched if shown_verdict(p) in ("careful", "skip")]

        b["rollup"] = {
            "products": len(rows),
            "researched": len(researched),
            "flagged": len(flagged),
            "worst": max((shown_verdict(p) for p in flagged),
                         key=lambda v: RANK.get(v, 0), default=None),
        }

        if not researched:
            no_products += 1
            continue
        if not flagged:
            continue

        old = b.get("stance")
        # One flagged product means "it depends which one", which is careful.
        # It never means skip, and it never softens a skip already in place.
        if RANK.get(old, 0) >= 1:
            already += 1
            continue

        b["stance"] = "careful"
        b["rollupApplied"] = True
        names = ", ".join(p.get("name") or "?" for p in flagged[:3])
        b["rollupNote"] = (
            f"{len(flagged)} of {len(researched)} products we have reviewed under this "
            f"brand are flagged: {names}"
            + ("…" if len(flagged) > 3 else "")
            + ". The verdict depends which one you pick.")
        moved += 1
        reasons[old] += 1
        moves.append((b["brand"], old, len(flagged), len(researched), names))

    print(f"brands: {len(brands)}")
    print(f"  no researched products, stance untouched: {no_products}")
    print(f"  already careful or skip:                  {already}")
    print(f"  moved to careful by the rollup:           {moved}")
    print(f"     from: {dict(reasons)}")

    if args.show or moved <= 25:
        print("\nbrands that move:")
        for name, old, f, r, names in sorted(moves):
            print(f"  {name:<26} {old:<8} -> careful   {f}/{r} flagged: {names[:64]}")

    if args.write:
        DATA.write_text(json.dumps(brands, indent=2, ensure_ascii=False) + "\n")
        print(f"\nwrote {DATA.name}")
    else:
        print("\ndry run. re-run with --write to apply.")


# ---------------------------------------------------------------- fronts
# What a product row's front had to come from before it may appear on the
# brand card. `inferred` is the classifier guessing from a product name and
# `rollup` would be this function reading its own output, so neither counts.
ROLLABLE = {"database", "hand", "stated", "class"}


def roll_fronts(brands):
    """A brand's own researched products fill in its scorecard.

    The verdict rollup above answers "is the brand careful". This answers the
    next question a Brand Check page asks, which is what we actually checked,
    and until now it answered nothing at all: this function sat below the
    __main__ guard and no caller ever reached it. Every brand card in the
    database was showing four blanks over product rows that had four recorded
    answers.

    That silence had a visible cost. enforce-scorecard will not print "Good
    choice" over an empty scorecard, which is the right rule and the reason
    HealthyBaby cannot happen again. With nothing ever filling the scorecard,
    184 brands had a stance a person had set to good parked at neutral, which
    Brand Check renders as "Context". Matyz is the top pick of the pumping
    guide and looked up as Context. So did Spectra, LacTeck, Thorne, Natracare,
    Saalt, Bobbie, DivaCup and a hundred more: the site recommending a brand in
    an article and declining to say so on its own brand page.

    Adverse evidence still wins, rule 1.1, and a single caution on one product
    is a fact about the brand worth showing. What is new is that a favourable
    front rolls up too, because the brand card's scorecard is not a claim about
    the rest of the range. It is the record of what was checked, which is
    exactly the question the gate asks. Whether the verdict itself reaches an
    unresearched product is decided by `generalises` and by the brand-line
    rows, both of which are untouched here.

    Two limits keep it honest. Only a front recorded by research counts, never
    one the classifier inferred, so nothing is laundered onto a brand card by
    guessing. And the note always names the product it came from, so a reader
    sees the evidence is about one thing rather than the whole catalogue.
    """
    RANK = {"caution": 1, "fail": 2}
    # A pass is stronger evidence of having looked than a `none`, which says
    # only that no evidence of that kind exists. Either satisfies the gate.
    GOOD = {"pass": 2, "none": 1}
    filled = adverse = favourable = 0
    for b in brands:
        fronts = b.setdefault("fronts", {})
        for f in ("formula", "materials", "legal", "testing"):
            cur = fronts.get(f)
            status = cur.get("status") if isinstance(cur, dict) else None
            if status not in (None, "", "unknown"):
                continue
            worst, source = None, None
            best, bsource = None, None
            for p in (b.get("products") or []):
                if p.get("origin") == "brand-line":
                    continue
                e = p.get("ext") or {}
                if (e.get("frontOrigin") or {}).get(f) not in ROLLABLE:
                    continue
                v = (e.get("fronts") or {}).get(f)
                if v in RANK and RANK[v] > RANK.get(worst or "", 0):
                    worst, source = v, p
                elif v in GOOD and GOOD[v] > GOOD.get(best or "", 0):
                    best, bsource = v, p
            if worst:
                pick, source, adverse = worst, source, adverse + 1
            elif best:
                pick, source, favourable = best, bsource, favourable + 1
            else:
                continue
            note = ((source.get("ext") or {}).get("frontNotes") or {}).get(f) or ""
            fronts[f] = {
                "status": pick,
                "note": (f"From {source.get('name')}: {note}" if note
                         else f"From {source.get('name')}.")[:400],
                "origin": "rollup",
            }
            filled += 1
    return filled, adverse, favourable


if __name__ == "__main__":
    sys.exit(main())
