#!/usr/bin/env python3
"""
Roll product verdicts up into the brand stance for Brand Check.

The two surfaces answer different questions and are deliberately not the same
system:

  Extension    "is THIS product safe?"  Strict, per product, no inheritance.
                A recommendation needs direct evidence about the exact thing on
                screen. See tools/audit-product-rules.py.

  Brand Check  "what do we make of this brand?"  A brand keeps its own stance
                and lists its products underneath, and the presence of a single
                flagged product is itself a fact about the brand worth showing.

The rollup rule: if any researched product under a brand is careful or skip, the
brand is at least careful. One bad product does not condemn a company, so a skip
product produces a careful brand, not a skip brand. What it means is "the answer
depends which product you pick", which is exactly what the shopper needs to know
before they read a single line further.

Two things are excluded from the rollup:

  brand-line rows, because they are generated by projecting the brand stance
  onto a category. Rolling them back up would be circular, the brand's own
  verdict returning to it dressed as evidence.

  an existing skip brand, which is never softened to careful. The rollup only
  ever tightens.

    python3 tools/brand-rollup.py             # report only
    python3 tools/brand-rollup.py --write
    python3 tools/brand-rollup.py --show      # list every brand that moves
"""

import argparse
import collections
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "brand-data.json"

RANK = {"good": 0, "neutral": 0, "careful": 1, "skip": 2}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--show", action="store_true", help="list every brand that moves")
    args = ap.parse_args()

    brands = json.loads(DATA.read_text())
    moved, moves = 0, []
    already = no_products = 0
    reasons = collections.Counter()

    for b in brands:
        rows = b.get("products") or []
        # Only independently researched rows count as evidence about the brand.
        researched = [p for p in rows if p.get("origin") != "brand-line"]
        flagged = [p for p in researched if p.get("verdict") in ("careful", "skip")]

        b["rollup"] = {
            "products": len(rows),
            "researched": len(researched),
            "flagged": len(flagged),
            "worst": max((p.get("verdict") for p in flagged),
                         key=lambda v: RANK.get(v, 0), default=None),
        }

        if not researched:
            no_products += 1
            continue
        if not flagged:
            continue

        old = b.get("stance")
        # One flagged product means "it depends which one", which is careful.
        # It never means skip, and it never softens a skip already in place.
        if RANK.get(old, 0) >= 1:
            already += 1
            continue

        b["stance"] = "careful"
        b["rollupApplied"] = True
        names = ", ".join(p.get("name") or "?" for p in flagged[:3])
        b["rollupNote"] = (
            f"{len(flagged)} of {len(researched)} products we have reviewed under this "
            f"brand are flagged: {names}"
            + ("…" if len(flagged) > 3 else "")
            + ". The verdict depends which one you pick.")
        moved += 1
        reasons[old] += 1
        moves.append((b["brand"], old, len(flagged), len(researched), names))

    print(f"brands: {len(brands)}")
    print(f"  no researched products, stance untouched: {no_products}")
    print(f"  already careful or skip:                  {already}")
    print(f"  moved to careful by the rollup:           {moved}")
    print(f"     from: {dict(reasons)}")

    if args.show or moved <= 25:
        print("\nbrands that move:")
        for name, old, f, r, names in sorted(moves):
            print(f"  {name:<26} {old:<8} -> careful   {f}/{r} flagged: {names[:64]}")

    if args.write:
        DATA.write_text(json.dumps(brands, indent=2, ensure_ascii=False) + "\n")
        print(f"\nwrote {DATA.name}")
    else:
        print("\ndry run. re-run with --write to apply.")


if __name__ == "__main__":
    sys.exit(main())
